# Uncomment this line to define a global platform for your project
platform :ios, '6.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'ZYChat' do

pod 'HyphenateSDK', '~> 3.1.2'

end

target 'ZYChatTests' do

end

